sneakers/Models/SneakersViewModels/MyProfileViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace sneakers.Models.SneakersViewModels
{
    public class MyProfileViewModel
    {
        public ApplicationUser CurrUser { get; set; }
        public List<Review> UserReviews { get; set; }
        public List<Sneaker> UserSneakers { get; set; }
    }
}

sneakers/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using sneakers.Data;
using sneakers.Models;
using sneakers.Models.ReviewsViewModels;

namespace sneakers.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ReviewsController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);


        // GET: Reviews
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Review.Include(r => r.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Reviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // GET: Reviews/Create
        public async Task<IActionResult> Create(string userId)
        {
            var user2BeReviewed = await _context.Users.FindAsync(userId);
            var currUser = await GetCurrentUserAsync();
            ViewBag.currUser = currUser.FirstName;
            // reframe from letting user create a review for themselves!
            if (currUser == user2BeReviewed)
            {
                return RedirectToAction("Index", "Sneakers");
            }
            

            ReviewsCreateViewModel viewModel = new ReviewsCreateViewModel
            {
                User = user2BeReviewed
            };

            return View(viewModel);
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ReviewsCreateViewModel viewModel)
        {
            ModelState.Remove("Review.User");
            ModelState.Remove("Review.UserId");
            ModelState.Remove("User.FirstName");
            ModelState.Remove("User.LastName");
            ModelState.Remove("Review.ReviewId");
            ModelState.Remove("Review.Rating");


            var reviewedUser = _context.Users.Find(viewModel.User.Id);
            viewModel.User = reviewedUser;
           

            if (ModelState.IsValid)
            {
                var review = viewModel.Review;
                review.User = viewModel.User;
                review.User.Rating = await CalculateRating(viewModel.User.Id);
                _context.Add(review);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("UserProfile", "Sneakers", new { userId4Profile = viewModel.User.Id });

        }

        // GET: Reviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review.FindAsync(id);
            if (review == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", review.UserId);
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReviewId,Rating,UserId")] Review review)
        {
            if (id != review.ReviewId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.ReviewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", review.UserId);
            return View(review);
        }

        // GET: Reviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var review = await _context.Review.FindAsync(id);
            _context.Review.Remove(review);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private async Task<double> CalculateRating(string userId)
        {
            double total = 0.0;
            int count = 0;
            double rating = 0.0;

            // grab the user
            var user = await _context.Users
                .Include(u => u.Reviews)
                .Where(u => u.Id == userId)
                .FirstAsync();

            // this foreach will go through each review that is generated for 
            // a user and add all the ratings so then we can get an average
            foreach (var item in user.Reviews)
            {
                count++;
                total += item.Rating;
            }


            // get the average and return 
            rating = total / count;
            var checkingRatingValue = double.IsNaN(rating);
            if (!checkingRatingValue)
            {
                return rating;
            }
            else
            {
                rating = 0.0;
                return rating;
            }
        }
        private bool ReviewExists(int id)
        {
            return _context.Review.Any(e => e.ReviewId == id);
        }
    }
}

sneakers/Controllers/SneakersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using sneakers.Data;
using sneakers.Models;
using sneakers.Models.SneakersViewModels;

namespace sneakers.Controllers
{
    public class SneakersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment hostingEnvironment;

        public SneakersController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _userManager = userManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Sneakers
        [Authorize]
        public async Task<IActionResult> Index(string searchString, string SearchBar)
        {
            ViewData["CurrentFilter"] = searchString;
            ViewData["SearchBar"] = SearchBar;

            var currentUser = GetCurrentUserAsync().Result;
            IQueryable<Sneaker> sneakers = _context.Sneaker
                .Include(s => s.Brand)
                .Include(s => s.Condition)
                .Include(s => s.Size)
                .Include(s => s.User)
                .Where(s => s.IsSold == false);




            if (!String.IsNullOrEmpty(searchString))
            {
                switch (SearchBar)
                {
                    case "1":
                        
                        sneakers = sneakers.Where(s => s.Brand.BrandType.ToUpper().Contains(searchString.ToUpper()));
                        break;
                    case "2":
                        sneakers = sneakers.Where(s => s.Size.ShoeSize.ToUpper().Contains(searchString.ToUpper()));
                        break;
                    case "3":
                        sneakers = sneakers.Where(s => s.Condition.ConditionType.ToUpper().Contains(searchString.ToUpper()));
                        break;
                    default:
                        //products.Where(p => p.Title.ToUpper().Contains(searchString.ToUpper())
                        //               || p.City.ToUpper().Contains(searchString.ToUpper()))
                        sneakers = sneakers.Where(s => s.Condition.ConditionType.ToUpper().Contains(searchString.ToUpper())
                                            || s.Brand.BrandType.ToUpper().Contains(searchString.ToUpper())
                                            || s.Size.ShoeSize.ToUpper().Contains(searchString.ToUpper()));
                        break;
                }

            }
            
            return View(await sneakers.ToListAsync());
        }

        // GET: Sneakers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sneaker = await _context.Sneaker
                .Include(s => s.Brand)
                .Include(s => s.Condition)
                .Include(s => s.Size)
                .Include(s => s.User)
                .FirstOrDefaultAsync(m => m.SneakerId == id);
            if (sneaker == null)
            {
                return NotFound();
            }

            return View(sneaker);
        }

        // GET: Sneakers/Create
        [Authorize]
        public async Task<IActionResult> Create()
        {
            var viewModel = new SneakersCreateViewModel
            {
                AvailableBrands = await _context.Brand.ToListAsync(),
                AvailableConditions = await _context.Condition.ToListAsync(),
                AvailableSizes = await _context.Size.ToListAsync()
            };

            return View(viewModel);
        }

        // POST: Sneakers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SneakersCreateViewModel viewModel)
        {
            ModelState.Remove("Sneaker.Brand");
            ModelState.Remove("Sneaker.Condition");
            ModelState.Remove("Sneaker.Size");
            ModelState.Remove("Sneaker.User");
            ModelState.Remove("Sneaker.UserId");


            // If the Photo property on the incoming model object is not null, then the user
            // has selected an image to upload.
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;

                // If the Photo property on the incoming model object is not null, then the user
                // has selected an image to upload.
                if (viewModel.Photo != null)
                {
                    // The image must be uploaded to the images folder in wwwroot
                    // To get the path of the wwwroot folder we are using the inject
                    // HostingEnvironment service provided by ASP.NET Core
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    // To make sure the file name is unique we are appending a new
                    // GUID value and and an underscore to the file name
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + viewModel.Photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    // Use CopyTo() method provided by IFormFile interface to
                    // copy the file to wwwroot/images folder
                    viewModel.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                var sneaker = viewModel.Sneaker;
                var currUser = await GetCurrentUserAsync();
                sneaker.ImgPath = uniqueFileName;
                sneaker.UserId = currUser.Id;
                _context.Add(sneaker);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            viewModel.AvailableBrands = await _context.Brand.ToListAsync();
            viewModel.AvailableConditions = await _context.Condition.ToListAsync();
            viewModel.AvailableSizes = await _context.Size.ToListAsync();

            return View(viewModel);
        }

        // GET: Sneakers/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            /*
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            var viewModel = new BookEditViewModel
            {
                Book = book,
                AvailableAuthors = await _context.Author.ToListAsync()
            };
            return View(viewModel);
             */
            // if the id that was passed in if null, then an error is thrown
            if (id == null)
            {
                return NotFound();
            }

            var sneaker = await _context.Sneaker.FindAsync(id);
            if (sneaker == null)
            {// if the sneaker from the db that was passed in if null, then an error is thrown
                return NotFound();
            }
            var viewModel = new SneakersEditViewModel
            {
                Sneaker = sneaker,
                AvailableBrands = await _context.Brand.ToListAsync(),
                AvailableConditions = await _context.Condition.ToListAsync(),
                AvailableSizes = await _context.Size.ToListAsync()
            };

            return View(viewModel);
        }

        // POST: Sneakers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SneakersEditViewModel viewModel)
        {

            var sneaker = viewModel.Sneaker;
            var sneaker4Image = viewModel.Sneaker.ImgPath;

            if (id != sneaker.SneakerId)
            {
                return NotFound();
            }

            ModelState.Remove("Sneaker.Brand");
            ModelState.Remove("Sneaker.Condition");
            ModelState.Remove("Sneaker.Size");
            ModelState.Remove("Sneaker.User");
            ModelState.Remove("Sneaker.UserId");

            string uniqueFileName = null;

            if (viewModel.Photo != null)
            {
                string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + viewModel.Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                viewModel.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
            }

            if (ModelState.IsValid)
            {
                try
                {
                    
                    var currentUser = await GetCurrentUserAsync();
                    sneaker.UserId = currentUser.Id;
                    sneaker.User = currentUser;
                    if(uniqueFileName != null)
                    {
                        sneaker.ImgPath = uniqueFileName;
                    }
                    else
                    {

sneakers/Views/Sneakers/Create.cshtml
@model sneakers.Models.SneakersViewModels.SneakersCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<div class="indexHeader"><img src="~/appImages/put.png" /></div>

<h4>Create a new sneaker!</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" method="post" asp-controller="Sneakers">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Sneaker.Title" class="control-label"></label>
                <input asp-for="Sneaker.Title" class="form-control" />
                <span asp-validation-for="Sneaker.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sneaker.Description" class="control-label"></label>
                <input asp-for="Sneaker.Description" class="form-control" />
                <span asp-validation-for="Sneaker.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sneaker.SizeId" class="control-label"></label>
                <select asp-for="Sneaker.SizeId" class="form-control" asp-items="@Model.SizeOptions"></select>
                <span asp-validation-for="Sneaker.SizeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sneaker.BrandId" class="control-label"></label>
                <select asp-for="Sneaker.BrandId" class="form-control" asp-items="@Model.BrandOptions"></select>
                <span asp-validation-for="Sneaker.BrandId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sneaker.ConditionId" class="control-label"></label>
                <select asp-for="Sneaker.ConditionId" class="form-control" asp-items="@Model.ConditionOptions"></select>
                <span asp-validation-for="Sneaker.ConditionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sneaker.Price" class="control-label"></label>
                <input asp-for="Sneaker.Price" class="form-control" />
                <span asp-validation-for="Sneaker.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
                <div class="custom-file">
                    <input asp-for="Photo" class="form-control custom-file-input" accept="image">
                    <label class="custom-file-label">Choose File...</label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>

            @section Scripts {
                <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
                @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
            }
                </script>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"><i class="fas fa-arrow-circle-left fa-2x"></i></a>
</div>

@*@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

sneakers/Views/Sneakers/Delete.cshtml
@model sneakers.Models.Sneaker

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sneaker</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Size)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Size.ShoeSize)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand.BrandType)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsSold)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsSold)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Condition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Condition.ConditionType)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImgPath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImgPath)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SneakerId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

sneakers/Views/Sneakers/Details.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

@model sneakers.Models.Sneaker

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Sneaker</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Size)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Size.ShoeSize)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Brand.BrandType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Condition)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Condition.ConditionType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImgPath)
        </dt>
        <dd>
            @*@{var photoPath = "~/images/" + (@Model.ImgPath ?? "noimage.jpg"); }*@
            <img class="card-img-top imageThumbnail" src="~/images/@Model.ImgPath"
                    asp-append-version="true" />
        </dd>
        <dd class="btn btn-primary">
            @{var currentUserId = SignInManager.UserManager.GetUserId(User);}
            <a class="text-light" asp-action="Chat" asp-controller="Messages" asp-route-otherUserId="@Model.UserId" asp-route-sneakerId="@Model.SneakerId">Message</a>
        </dd>
    </dl>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.SneakerId">Edit</a> |*@
    <a asp-action="Index"><i class="fas fa-arrow-circle-left fa-2x"></i></a>
</div>

<div class="detailsContainer">
    <div class="detailSneaker">
        <div class="card">
            @{var photoPath = "~/images/" + (@Model.ImgPath ?? "noimage.jpg"); }
            <img class="card-img-top imageThumbnail" src="~/images/@Model.ImgPath"
                 asp-append-version="true" />
            <div class="card-body">@Model.Title</div>
        </div>
    </div>
    <div class="detailInfo">
        <div class="card">
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">@Model.Description</li>
                    <li class="list-group-item">@Model.Price</li>
                    <li class="list-group-item">@Model.Brand.BrandType</li>
                    <li class="list-group-item">@Model.Size</li>
                    <li class="list-group-item">@Model.Condition.ConditionType</li>
                </ul>
            </div>
        </div>
    </div>
</div>

sneakers/Views/Sneakers/EditProfile.cshtml
@model sneakers.Models.SneakersViewModels.MyProfileEditViewModel

@{
    ViewData["Title"] = "EditProfile";
}

<div class="indexHeader"><img src="~/appImages/put.png" /></div>


<h2>Edit Your Profile</h2>
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditProfile" enctype="multipart/form-data" asp-controller="Sneakers">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                @*<label asp-for="@Model.User.ImgPath" class="control-label"></label>*@

                @{var photoPath = "~/images/" + (Model.User.ImgPath ?? "noimage.jpg");}
                <img class="card-img-top imageThumbnail" src="~/images/@Model.User.ImgPath"
                     asp-append-version="true" />
            </div>
            <hr/>
            <div class="form-group">
                <label asp-for="Photo" class="col-form-label">New Profile Picture</label>
                <div class="col-sm-10">
                    <input asp-for="Photo" class="form-control custom-file-input" accept="image">
                    <label class="custom-file-label">Choose File...</label>
                </div>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="@Model.User.ImgPath" />
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
            @section Scripts {
                <script>
                    $(document).ready(function () {
                        $('.custom-file-input').on("change", function () {
                            var fileName = $(this).val().split("\\").pop();
                            $(this).next('.custom-file-label').html(fileName);
                        });
                        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
                    }
                </script>
            }
        </form>
    </div>
</div>

sneakers/Views/Sneakers/UserProfile.cshtml
@model sneakers.Models.SneakersViewModels.UserProfileViewModel

@{
    ViewData["Title"] = "User Profile";
}
<h1 class="userProfileHeader">@Model.User.FirstName's Profile</h1>
<div class="profile">
    <div class="card">
        <div class="card-header blackBack font-weight-bold">
            @Model.User.FirstName @Model.User.LastName
        </div>
        <div class="card-body blackBack">
            <div class="card">
                @if (Model.User.ImgPath != null)
                {
                    <img class="card-img-top imageThumbnail" src="~/images/@Model.User.ImgPath"
                         asp-append-version="true" />
                }
                <div class="card-body blackBack">
                    Rating: @Model.User.Rating
                </div>
                <a class=" blackBack btn btn-outline-info"  asp-action="Create" asp-controller="Reviews" asp-route-userId="@Model.User.Id">Write a review!</a>
            </div>
        </div>
    </div>
    <div class="reviewsProfile">
        <div class="reviewsProfile card text-center">
            <div class="card-header blackBack font-weight-bold">
                Reviews about @Model.User.FirstName
            </div>
            @foreach (var item in @Model.AllReviews)
            {
                <div class="card-body blackBack">
                    <div class="card">
                        <div class="card-body blackBack">
                            <span>Reviewer: @item.ReviewerName</span>
                            <div>@item.ReviewMessage</div>
                            <div>Rating: @item.Rating</div>
                        </div>
                    </div>
                </div>
            }
        </div>

    </div>
    <div class="sneakersProfile card text-center">
        <div class="card-header blackBack font-weight-bold">@Model.User.FirstName's Other Sneakers</div>
        @foreach (var item in @Model.AllSneakers)
        {
            <div class="card-body blackBack">
                <div class="card">
                    <div class="card-header blackBack">@item.Title</div>
                    <div class="card-body blackBack">
                        @{var photoPath = "~/images/" + (item.ImgPath ?? "noimage.jpg"); }
                        <img class="card-img-top imageThumbnail" src="~/images/@item.ImgPath"
                             asp-append-version="true" />
                    </div>
                    <a class=" blackBack btn btn-outline-success" asp-action="Details" asp-route-id="@item.SneakerId">Details</a>
                </div>
            </div>
        }
    </div>
</div>