sneakers/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using sneakers.Data;
using sneakers.Models;
using sneakers.Models.MessagesViewModels;

namespace sneakers.Controllers
{
    public class MessagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IConfiguration _config;

        public SqlConnection Connection
        {
            get
            {
                return new SqlConnection(_config.GetConnectionString("DefaultConnection"));
            }
        }
        public MessagesController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager, IConfiguration config)
        {
            _context = context;
            _userManager = userManager;
            _config = config;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Messages
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Message.Include(m => m.Sender).Include(m => m.Sneaker);
            return View(await applicationDbContext.ToListAsync());
        }

        [Authorize]
        // GET: This method will return a list of conversations
        public async Task<IActionResult> ListConversations()
        {
            using (SqlConnection conn = Connection)
            {
                conn.Open();
                using (SqlCommand cmd = conn.CreateCommand())
                {
                    // get messages where the curr user is the seller , I want all messages where ppl sent me 
                    cmd.CommandText = @"SELECT DISTINCT m.SneakerId, m.SenderId
                                        FROM Message m
                                        INNER JOIN Sneaker s ON s.SneakerId = m.SneakerId
                                        WHERE m.ReceiverId = @theUserId
                                        AND s.UserId = @theUserId;";

                    // parameters
                    var currentUser = await GetCurrentUserAsync();
                    cmd.Parameters.Add(new SqlParameter("@theUserId", currentUser.Id));

                    SqlDataReader reader = cmd.ExecuteReader();
                    List<ConversationsViewModel> Conversations = new List<ConversationsViewModel>();
                    

                    while (reader.Read())
                    {
                        ConversationsViewModel convo = new ConversationsViewModel
                        {
                            SneakerId = reader.GetInt32(reader.GetOrdinal("SneakerId")),
                            UserId = reader.GetString(reader.GetOrdinal("SenderId")),
                            Sneaker = _context.Sneaker.Find(reader.GetInt32(reader.GetOrdinal("SneakerId"))),
                            OtherUserId = reader.GetString(reader.GetOrdinal("SenderId")),
                            OtherUser = _context.Users.Find(reader.GetString(reader.GetOrdinal("SenderId")))
                        };
                        Conversations.Add(convo);
                    }
                    reader.Close();

                    // get me the messages where the curr 
                    cmd.CommandText = @"SELECT DISTINCT m.SneakerId, m.ReceiverId
                                        FROM Message m
                                        INNER JOIN Sneaker s ON s.SneakerId = m.SneakerId
                                        WHERE m.SenderId = @curr
                                        AND s.UserId != @curr;";

                    cmd.Parameters.Add(new SqlParameter("@curr", currentUser.Id));
                    SqlDataReader reader1 = cmd.ExecuteReader();

                    while (reader1.Read())
                    {
                        ConversationsViewModel convo = new ConversationsViewModel
                        {
                            SneakerId = reader1.GetInt32(reader1.GetOrdinal("SneakerId")),
                            UserId = currentUser.Id,
                            Sneaker = _context.Sneaker.Find(reader1.GetInt32(reader1.GetOrdinal("SneakerId"))),
                            OtherUserId = reader1.GetString(reader1.GetOrdinal("ReceiverId")),
                            OtherUser = _context.Users.Find(reader1.GetString(reader1.GetOrdinal("ReceiverId")))
                        };
                        Conversations.Add(convo);
                        //ViewBag.OtherUserId = reader1.GetString(reader1.GetOrdinal("ReceiverId"));
                        //var otherPerson = _context.Users.Find(reader1.GetString(reader1.GetOrdinal("ReceiverId")));
                        //ViewBag.OtherUserName = otherPerson.FirstName;
                        
                    }
                    reader1.Close();
                    
                    return View(Conversations);
                }
            }
        }

        [Authorize]
        // GET: All this does is get the chatMessages for one conversation 
        public async Task<IActionResult> Chat(int sneakerId, string otherUserId)
        {
            // userId is the buyer, sneakerId is for the sneaker for sale
            using (SqlConnection conn = Connection)
            {
                conn.Open();
                using (SqlCommand cmd = conn.CreateCommand())
                {
                    cmd.CommandText = @"SELECT MessageId, Msg, Date,
                                               SneakerId, SenderId, ReceiverId
                                        FROM Message
                                        WHERE SneakerId = @sneakerId
                                        AND (SenderId = @userId
                                                AND ReceiverId = @otherUserId)
                                        ORDER BY Date;";

                    var currentUser = await GetCurrentUserAsync();
                    //var curruserId = currentUser.Id;
                    var sneakerInQuestion = _context.Sneaker
                        .Include(u => u.User)
                        .FirstOrDefault(s => s.SneakerId == sneakerId);

                    ViewBag.SneakerOwnerId = sneakerInQuestion.UserId;
                    ViewBag.SneakerOwner = sneakerInQuestion.User.FirstName;
                    ViewBag.currUserName = currentUser.FirstName;

                    cmd.Parameters.Add(new SqlParameter("@userId", currentUser.Id));
                    cmd.Parameters.Add(new SqlParameter("@otherUserId", otherUserId));
                    cmd.Parameters.Add(new SqlParameter("@sneakerId", sneakerId));

                    SqlDataReader reader = await cmd.ExecuteReaderAsync();
                    List<Message> messages = new List<Message>();

                    while (reader.Read())
                    {
                        Message message = new Message
                        {
                            MessageId = reader.GetInt32(reader.GetOrdinal("MessageId")),
                            Msg = reader.GetString(reader.GetOrdinal("Msg")),
                            Date = reader.GetDateTime(reader.GetOrdinal("Date")),
                            SneakerId = reader.GetInt32(reader.GetOrdinal("SneakerId")),
                            SenderId = reader.GetString(reader.GetOrdinal("SenderId")),
                            ReceiverId = reader.GetString(reader.GetOrdinal("ReceiverId"))
                        };
                        messages.Add(message);
                    }
                    reader.Close();

                    cmd.CommandText = @"SELECT MessageId, Msg, Date,
                                               SneakerId, SenderId, ReceiverId
                                        FROM Message
                                        WHERE SneakerId = @theSneakerId
                                        AND (SenderId = @theOtherUserId
                                                AND ReceiverId = @currUserId)
                                        ORDER BY Date;";


                    cmd.Parameters.Add(new SqlParameter("@currUserId", currentUser.Id));
                    cmd.Parameters.Add(new SqlParameter("@theOtherUserId", otherUserId));
                    cmd.Parameters.Add(new SqlParameter("@theSneakerId", sneakerId));

                    SqlDataReader reader1 = await cmd.ExecuteReaderAsync();
                    while (reader1.Read())
                    {
                        Message message = new Message
                        {
                            MessageId = reader1.GetInt32(reader1.GetOrdinal("MessageId")),
                            Msg = reader1.GetString(reader1.GetOrdinal("Msg")),
                            Date = reader1.GetDateTime(reader1.GetOrdinal("Date")),
                            SneakerId = reader1.GetInt32(reader1.GetOrdinal("SneakerId")),
                            SenderId = reader1.GetString(reader1.GetOrdinal("SenderId")),
                            ReceiverId = reader1.GetString(reader1.GetOrdinal("ReceiverId"))
                        };
                        messages.Add(message);
                    }
                    reader1.Close();

                    var sneaker = _context.Sneaker.Find(sneakerId);
                    ViewBag.User = currentUser.FirstName;

                    var otherUser = _context.Users.Find(otherUserId);

                    ViewBag.OtherUser = otherUser.FirstName;
                    ViewBag.OtherUserImg = otherUser.ImgPath;

                    var viewModel = new ChatMessagesViewModel
                    {

sneakers/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - sneakers</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/StyleSheet.css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/StyleSheet.css" />
    <link rel="stylesheet" href="@Url.Content("~/Style.css")" type="text/css" />
    @RenderSection("Style", false)
    <script src="https://kit.fontawesome.com/448a782f99.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <a class="navbar-brand"><img src="~/appImages/logo.png" width="60" height="40" class="d-inline-block align-top" /></a>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Sneakers" asp-action="Index">Sneakers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Messages" asp-action="ListConversations">Messages</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Sneakers" asp-action="MySneakers">My Kicks</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Sneakers" asp-action="MyProfile">My Profile</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @*<partial name="_CookieConsentPartial" />*@
        @*<main role="main" class="pb-3">
        </main>*@
            @RenderBody()
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - sneakers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>